name: gym_rl
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - box2d-py
  - ffmpeg
  - pip
  - pip:
      - gymnasium==1.2.2
      - pygame==2.1.3
      - tensorboard==2.20.0
      - tqdm
      - moviepy
